#!/usr/bin/env python3
import sys
from core import set_language, run_tool

STRINGS = {
    "pause": "Press Enter to return…",
    "open_yn": "open ? (y/n) >>",
    "yes": "Yes", "no": "No",
    "username": "Username", "display": "Display", "created": "Created",
    "banned": "Banned", "verified": "Verified", "friends": "Friends",
    "followers": "Followers", "following": "Following",
    "status": "Status", "in_game": "In game", "description": "Description",
    "name": "Name", "creator": "Creator", "price": "Price", "sales": "Sales",
    "playing": "Playing", "visits": "Visits", "max_players": "Max players",
    "members": "Members", "public": "Public", "owner_id": "Owner ID",
    "assets": "Assets", "equipped": "Equipped assets",
    "status_off": "Offline", "status_on": "Online",
    "status_game": "In-Game", "status_studio": "Studio",
    "off_sale": "Off sale",
    "invalid_cookie": "INVALID — expired or invalid cookie",
    "user_not_found": "User not found",
    "unknown_tool": "Unknown tool:",
    "cancelled": "cancelled", "error": "Error:", "network": "Network unreachable",
    "cookie_title": "ROBLOX COOKIE CHECKER",
    "cookie_desc": "Validate a .ROBLOSECURITY cookie via Roblox API",
    "cookie_prompt": "cookie (.ROBLOSECURITY)",
    "cookie_ok": "Valid cookie",
    "user_title": "ROBLOX USERNAME LOOKUP",
    "user_desc": "Username or ID → public profile",
    "user_prompt": "username or user id",
    "game_title": "ROBLOX GAME LOOKUP",
    "game_desc": "Place ID → game info",
    "place_prompt": "place id",
    "place_invalid": "Invalid place ID",
    "game_not_found": "Game not found",
    "game_details_fail": "Could not fetch game details",
    "group_title": "ROBLOX GROUP LOOKUP",
    "group_desc": "Group ID → public group info",
    "group_prompt": "group id",
    "group_invalid": "Invalid group ID",
    "group_not_found": "Group not found",
    "avatar_title": "ROBLOX AVATAR VIEWER",
    "avatar_desc": "View avatar + equipped assets",
    "robux_title": "ROBLOX ROBUX CHECKER",
    "robux_desc": "Robux balance for cookie account",
    "robux_fail": "Could not read balance",
    "account_title": "ROBLOX ACCOUNT CHECKER",
    "account_desc": "Full account analysis via cookie",
    "account_result": "Account Check",
    "profile_title": "ROBLOX PROFILE VIEWER",
    "profile_desc": "Detailed public profile",
    "item_title": "ROBLOX ITEM LOOKUP",
    "item_desc": "Asset ID → item details",
    "item_prompt": "asset / item id",
    "item_invalid": "Invalid asset ID",
    "item_not_found": "Item not found",
    "badge_title": "ROBLOX BADGE CHECKER",
    "badge_desc": "User badges (cookie required)",
    "badge_fail": "Badges unavailable",
    "badge_empty": "No badges found",
    "inv_title": "ROBLOX INVENTORY VIEW",
    "inv_desc": "Limiteds / collectibles (cookie required)",
    "inv_fail": "Inventory unavailable",
    "inv_empty": "No collectibles found",
    "uid_prompt": "user id (enter = {} for self)",
    "uid_invalid": "Invalid user ID",
    "fav_title": "ROBLOX GAME FAVORITES",
    "fav_desc": "Place ID → favorites & votes",
    "favorites": "Favorites",
    "roles_title": "ROBLOX GROUP ROLES",
    "roles_desc": "Group ID → role list",
    "limited_title": "ROBLOX LIMITED PRICE",
    "limited_desc": "Asset ID → limited / RAP price",
    "rap": "RAP (average)",
    "stock": "Remaining stock",
    "friends_title": "Friends List", "friends_desc": "Cookie required",
    "friends_empty": "No friends or invalid cookie",
    "follow_title": "Followers", "follow_desc": "Followers / following count",
    "age_title": "Account Age", "age_desc": "Join date",
    "gp_title": "Game Pass", "gp_desc": "Game pass ID lookup",
    "gamepass_id": "game pass id",
    "place_title": "Place → Universe", "place_desc": "Convert Place ID",
    "place_id": "place id",
    "cat_title": "Catalog Search", "cat_desc": "Search Roblox catalog",
    "search_q": "keyword",
    "multi_title": "Multi Cookie Check", "multi_desc": "Batch cookie validation",
    "multi_hint": "One cookie per line, empty line to finish",
    "export_title": "Export JSON", "export_desc": "Profile → data/exports/",
    "uid_only": "user id",
    "batch_title": "Avatar Batch", "batch_desc": "Space-separated user IDs",
    "uids_csv": "user ids",
    "gfunds_title": "Group Funds", "gfunds_desc": "Group Robux (cookie)",
    "group_id": "group id",
    "gfunds_note": "Requires group permissions",
    "not_found": "Not found",
    "robux": "Robux",
}

if __name__ == "__main__":
    set_language(STRINGS)
    run_tool(sys.argv[1] if len(sys.argv) > 1 else "")
