#!/usr/bin/env python3
import sys
from core import set_language, run_tool

STRINGS = {
    "pause": "Press Enter to return…",
    "yes": "Yes", "no": "No", "hidden": "hidden", "never": "Never",
    "cancelled": "Cancelled", "error_title": "Error", "unknown": "Unknown tool:",
    "network": "Network unreachable", "pick_mode": "Select mode",
    "tk_title": "Token Checker", "tk_desc": "Validate a Discord token",
    "tk_checking": "Validating token…",
    "token_prompt": "Discord token", "token_invalid": "Invalid token",
    "token_ok": "Valid token", "user": "User",
    "inv_title": "Invite Resolver", "inv_desc": "Code or link → server info",
    "inv_prompt": "Code or link (discord.gg/…)", "inv_invalid": "Invalid invite",
    "server": "Server", "members": "Members", "online": "Online",
    "channel": "Channel", "expires": "Expires",
    "user_title": "User Lookup", "user_desc": "User ID → snowflake decode + optional bot profile",
    "uid_prompt": "User ID (or mention)", "uid_invalid": "Invalid user ID",
    "user_bot_token": "Bot token (Enter = snowflake only)",
    "user_bot_invalid": "Invalid bot token — snowflake data shown",
    "user_fetch": "Fetching profile…", "user_result": "User lookup",
    "user_not_found_api": "User not found on Discord — snowflake data shown",
    "created": "Created", "created_local": "Created (local)", "age": "Account age",
    "avatar": "Avatar", "default_avatar": "Default avatar",
    "snowflake": "Timestamp (ms)", "token_prefix": "Token prefix",
    "display_name": "Display name", "badges": "Badges",
    "user_fail": "User not found", "token_hint": "Optional token unlocks username & avatar",
    "wh_title": "Webhook Info", "wh_desc": "Webhook URL → details",
    "wh_prompt": "Full webhook URL", "wh_invalid": "Invalid webhook URL",
    "wh_fail": "Webhook not found", "name": "Name", "type": "Type",
    "file_not_found": "File not found", "lines_hint": "One per line, empty line to finish",
    "guilds": "Guilds", "connections": "Connections", "billing_subs": "Billing subs",
    "ti_title": "Token Info", "ti_desc": "Account details from a valid token",
    "ti_fetch": "Fetching account data…",
    "ti_result": "Token details",
    "bf_title": "Token Bruteforce", "bf_desc": "Bruteforce token from User ID or check a list",
    "bf_mode": "Mode", "bf_mode_id": "User ID bruteforce", "bf_mode_list": "Bulk token check",
    "bf_prompt": "Token or type file", "bf_file": ".txt file path",
    "bf_delay": "Delay between checks (sec, default 0.5)",
    "bf_running": "Checking", "bf_result": "Results", "bf_summary": "Valid",
    "bf_save": "Save valid tokens? (yes/no)", "bf_saved": "Saved to",
    "bf_half": "Token prefix (base64 ID)", "bf_continue": "Bruteforce the rest? (yes/no)",
    "bf_proxy": "Use proxies? (yes/no)", "bf_proxy_type": "Proxy type (http/socks4/socks5)",
    "bf_scraping": "Scraping proxies…", "bf_proxies_loaded": "proxies loaded",
    "bf_bruting": "Bruteforcing…", "bf_found": "VALID TOKEN FOUND",
    "bf_stopped": "Stopped", "bf_attempts": "attempts", "bf_uid_invalid": "Invalid user ID",
    "bf_no_proxies": "No proxies found — try without proxies",
    "tl_title": "Token Login", "tl_desc": "Login to Discord in browser with your token",
    "tl_chrome": "Opening Chrome…", "tl_auto_ok": "Logged in — browser stays open",
    "tl_manual": "Chrome unavailable — manual mode", "tl_steps": "Manual login steps",
    "tl_opened": "Browser opened",
    "wd_title": "Webhook Destroyer", "wd_desc": "Delete a webhook permanently",
    "wd_confirm": "Delete this webhook? (yes/no)", "wd_ok": "Webhook deleted",
    "wd_fail": "Delete failed",
    "gl_title": "Guild Leaver", "gl_desc": "Leave all servers on an account",
    "gl_fetch_fail": "Could not fetch guild list", "gl_empty": "No guilds found",
    "gl_confirm": "Leave ALL guilds? (yes/no)",
    "gl_done": "Summary", "gl_left": "Left", "gl_deleted": "Deleted",
    "gl_running": "Leaving servers…", "gl_owner": "owner",
    "on_title": "Token Onliner", "on_desc": "Keep account(s) online via Gateway WebSocket",
    "on_single": "Single token", "on_file": "Token file",
    "on_ctrlc": "Ctrl+C to stop", "on_online": "Online", "on_stopped": "Stopped",
    "sr_title": "Status Rotator", "sr_desc": "Rotate custom status (REST API)",
    "sr_prompt": "Status, comma-list, or type file", "sr_file": ".txt file (one status/line)",
    "sr_delay": "Rotation interval (sec, default 15)", "sr_statuses": "statuses",
    "sr_active": "Rotator active", "sr_stopped": "Rotator stopped",
}

if __name__ == "__main__":
    set_language(STRINGS)
    run_tool(sys.argv[1] if len(sys.argv) > 1 else "")
