#!/usr/bin/env python3
import sys
from core import set_language, run_tool

STRINGS = {
    "pause": "Entrée pour revenir au menu…",
    "yes": "Oui", "no": "Non", "hidden": "masqué", "never": "Jamais",
    "cancelled": "Annulé", "error_title": "Erreur", "unknown": "Outil inconnu :",
    "network": "Connexion impossible", "pick_mode": "Choisir le mode",
    "tk_title": "Token Checker", "tk_desc": "Vérifie la validité d'un token Discord",
    "tk_checking": "Validation du token…",
    "token_prompt": "Token Discord", "token_invalid": "Token invalide",
    "token_ok": "Token valide", "user": "Utilisateur",
    "inv_title": "Invite Resolver", "inv_desc": "Code ou lien → infos du serveur",
    "inv_prompt": "Code ou lien (discord.gg/…)", "inv_invalid": "Invite invalide",
    "server": "Serveur", "members": "Membres", "online": "En ligne",
    "channel": "Salon", "expires": "Expiration",
    "user_title": "User Lookup", "user_desc": "ID user → decode snowflake + profil bot optionnel",
    "uid_prompt": "ID utilisateur (ou mention)", "uid_invalid": "ID utilisateur invalide",
    "user_bot_token": "Token bot (Entrée = snowflake seulement)",
    "user_bot_invalid": "Token bot invalide — données snowflake affichées",
    "user_fetch": "Récupération du profil…", "user_result": "User lookup",
    "user_not_found_api": "Utilisateur introuvable — données snowflake affichées",
    "created": "Création", "created_local": "Création (local)", "age": "Âge du compte",
    "avatar": "Avatar", "default_avatar": "Avatar par défaut",
    "snowflake": "Timestamp (ms)", "token_prefix": "Préfixe token",
    "display_name": "Nom affiché", "badges": "Badges",
    "user_fail": "Utilisateur introuvable", "token_hint": "Token optionnel pour pseudo & avatar",
    "wh_title": "Webhook Info", "wh_desc": "URL webhook → détails",
    "wh_prompt": "URL webhook complète", "wh_invalid": "URL webhook invalide",
    "wh_fail": "Webhook introuvable", "name": "Nom", "type": "Type",
    "file_not_found": "Fichier introuvable", "lines_hint": "1 par ligne, ligne vide pour finir",
    "guilds": "Serveurs", "connections": "Connexions", "billing_subs": "Abonnements",
    "ti_title": "Token Info", "ti_desc": "Détails du compte via un token valide",
    "ti_fetch": "Récupération des données…",
    "ti_result": "Détails du token",
    "bf_title": "Token Bruteforce", "bf_desc": "Bruteforce via ID user ou check de liste",
    "bf_mode": "Mode", "bf_mode_id": "Bruteforce ID user", "bf_mode_list": "Check liste tokens",
    "bf_prompt": "Token ou tape file", "bf_file": "Chemin fichier .txt",
    "bf_delay": "Délai entre checks (sec, défaut 0.5)",
    "bf_running": "Vérification de", "bf_result": "Résultats", "bf_summary": "Valides",
    "bf_save": "Sauvegarder les valides ? (yes/no)", "bf_saved": "Enregistré dans",
    "bf_half": "Préfixe token (base64 ID)", "bf_continue": "Bruteforcer la suite ? (yes/no)",
    "bf_proxy": "Utiliser des proxies ? (yes/no)", "bf_proxy_type": "Type proxy (http/socks4/socks5)",
    "bf_scraping": "Récupération proxies…", "bf_proxies_loaded": "proxies chargés",
    "bf_bruting": "Bruteforce en cours…", "bf_found": "TOKEN VALIDE TROUVÉ",
    "bf_stopped": "Arrêté", "bf_attempts": "tentatives", "bf_uid_invalid": "ID utilisateur invalide",
    "bf_no_proxies": "Aucun proxy trouvé — réessaie sans proxies",
    "tl_title": "Token Login", "tl_desc": "Connexion Discord navigateur avec le token",
    "tl_chrome": "Ouverture Chrome…", "tl_auto_ok": "Connecté — navigateur laissé ouvert",
    "tl_manual": "Chrome indisponible — mode manuel", "tl_steps": "Étapes connexion manuelle",
    "tl_opened": "Navigateur ouvert",
    "wd_title": "Webhook Destroyer", "wd_desc": "Supprime un webhook définitivement",
    "wd_confirm": "Supprimer ce webhook ? (yes/no)", "wd_ok": "Webhook supprimé",
    "wd_fail": "Échec de suppression",
    "gl_title": "Guild Leaver", "gl_desc": "Quitte tous les serveurs du compte",
    "gl_fetch_fail": "Impossible de récupérer les serveurs", "gl_empty": "Aucun serveur",
    "gl_confirm": "Quitter TOUS les serveurs ? (yes/no)",
    "gl_done": "Résumé", "gl_left": "Quittés", "gl_deleted": "Supprimés",
    "gl_running": "Leave en cours…", "gl_owner": "owner",
    "on_title": "Token Onliner", "on_desc": "Maintient le(s) compte(s) en ligne via Gateway",
    "on_single": "Un token", "on_file": "Fichier tokens",
    "on_ctrlc": "Ctrl+C pour arrêter", "on_online": "En ligne", "on_stopped": "Arrêté",
    "sr_title": "Status Rotator", "sr_desc": "Rotation statut perso (API REST)",
    "sr_prompt": "Statut, liste virgules, ou tape file", "sr_file": "Fichier .txt (1 statut/ligne)",
    "sr_delay": "Intervalle rotation (sec, défaut 15)", "sr_statuses": "statuts",
    "sr_active": "Rotator actif", "sr_stopped": "Rotator arrêté",
}

if __name__ == "__main__":
    set_language(STRINGS)
    run_tool(sys.argv[1] if len(sys.argv) > 1 else "")
