#!/usr/bin/env python3
import sys
from core import set_language, run_tool

STRINGS = {
    "pause": "Press Enter to return…",
    "yes": "Yes", "no": "No", "cancelled": "Cancelled", "pick_mode": "Select mode",
    "error_title": "Error", "unknown": "Unknown tool:", "network": "Network unreachable",
    "file_not_found": "File not found", "lines_hint": "One per line, empty line to finish",
    "name": "Name", "type": "Type", "created": "Created",
    "pub_tag": "https://discord.gg/007tools", "pub_short": "https://discord.gg/007tools · Wock-Multi v2",
    "pub_line": "**Wock-Multi** → https://discord.gg/007tools", "pub_user": "Wock-Multi",
    "wh_title": "Webhook Info", "wh_desc": "Webhook URL → channel, guild & metadata",
    "wh_prompt": "Full webhook URL", "wh_invalid": "Invalid webhook URL",
    "wh_fail": "Webhook not found", "wh_fetch": "Fetching webhook…",
    "wsg_title": "Send Message", "wsg_desc": "Test ping, custom, TTS, silent, fake user, mention, thread",
    "wsg_test": "Test ping", "wsg_custom": "Custom message", "wsg_tts": "TTS message",
    "wsg_silent": "Silent (no notification)", "wsg_fake": "Fake username/avatar", "wsg_mention": "Mention ping",
    "wsg_thread": "Thread / forum post",
    "wt_ping": "✔ Wock-Multi online — https://discord.gg/007tools",
    "wt_sending": "Sending…", "wt_ok": "Message sent", "wt_fail": "Send failed",
    "ws_title": "Webhook Spammer", "ws_desc": "Normal, mass threads, multi-URL, random words, embed spam",
    "ws_mode_normal": "Normal spam", "ws_mode_mass": "Mass (threads)", "ws_mode_multi": "Multi-webhook",
    "ws_mode_random": "Random words", "ws_mode_embed": "Embed spam",
    "ws_msg": "Message content", "ws_count": "Amount (1-100, default 10)",
    "ws_delay": "Delay between sends (sec, default 0.3)",
    "ws_name": "Webhook username (optional)", "ws_mention": "Add @everyone? (yes/no)",
    "ws_running": "Sending…", "ws_sent": "Sent", "ws_failed": "Failed",
    "wgf_title": "GIF & Bad Word Spammer", "wgf_desc": "GIF embeds, fast spam, bad words or mixed",
    "wgf_mode_gif": "GIF spam (embed)", "wgf_mode_fast": "Fast spam (GIF + word)",
    "wgf_mode_bad": "Bad word spam", "wgf_mode_mix": "GIF + bad word mix",
    "wgf_gifs": "GIF URLs (comma/file or Enter = defaults)",
    "wgf_badwords": "Bad words (comma/file or Enter = defaults)",
    "wgf_running": "Spamming…",
    "wms_title": "Mass Spammer", "wms_desc": "Parallel threaded spam (PEGPX-style)",
    "wms_threads": "Threads (1-8, default 4)", "wms_per": "Messages per thread (1-25, default 5)",
    "wms_running": "Mass spam running…",
    "wmu_title": "Multi-Webhook Spam", "wmu_desc": "Spam multiple webhook URLs at once",
    "wmu_result": "Multi-webhook results",
    "wrs_title": "Random Spammer", "wrs_desc": "Send random words from a list",
    "wrs_words": "Words (comma/file or Enter = defaults)",
    "we_title": "Embed Sender", "we_desc": "Send a rich embed through the webhook",
    "we_embed_title": "Embed title", "we_embed_desc": "Embed description",
    "we_color": "Color hex (default 880000)", "we_footer": "Footer text",
    "we_thumb": "Thumbnail URL (optional)", "we_default_desc": "Powered by Wock-Multi · https://discord.gg/007tools",
    "we_sending": "Sending embed…", "we_ok": "Embed sent", "we_fail": "Embed failed",
    "wse_title": "Embed Spammer", "wse_desc": "Spam colored embeds through the webhook",
    "wse_running": "Sending embeds…",
    "wj_title": "JSON Sender", "wj_desc": "Send a custom JSON payload to the webhook",
    "wj_hint": "Paste valid JSON (content, embeds, username…)",
    "wj_body": "JSON payload", "wj_invalid": "Invalid JSON",
    "wj_sending": "Sending payload…", "wj_ok": "Payload sent", "wj_fail": "Send failed",
    "wf_title": "File Sender", "wf_desc": "Send a file via webhook (local path or URL)",
    "wf_source": "File path or direct URL", "wf_caption": "Caption (optional)",
    "wf_download": "Downloading file…", "wf_ok": "File sent", "wf_fail": "Send failed",
    "wtts_title": "TTS Sender", "wtts_desc": "Send a text-to-speech message",
    "wtts_ok": "TTS message sent", "wtts_fail": "TTS failed",
    "wmn_title": "Mention Ping", "wmn_desc": "Ping @everyone or @here via webhook",
    "wmn_ok": "Mention sent", "wmn_fail": "Mention failed",
    "wg_title": "Ghost Ping", "wg_desc": "Send a message then delete it instantly",
    "wg_msg": "Message (default @everyone + pub)", "wg_delay": "Delete after (sec, default 1.5)",
    "wg_fail_send": "Send failed", "wg_no_id": "No message ID returned",
    "wg_wait": "Deleting in", "wg_ok": "Ghost ping done", "wg_fail_del": "Delete failed",
    "wt2_title": "Thread Sender", "wt2_desc": "Post into a forum/thread via thread_id",
    "wt2_thread": "Thread ID", "wt2_invalid": "Invalid thread ID",
    "wt2_ok": "Posted to thread", "wt2_fail": "Thread post failed",
    "wem_title": "Message Editor", "wem_desc": "Edit a message sent by this webhook",
    "wem_content": "New message content", "wem_ok": "Message edited", "wem_fail": "Edit failed",
    "wm_title": "Message Deleter", "wm_desc": "Delete a message sent by this webhook",
    "wm_id": "Message ID", "wm_id_invalid": "Invalid message ID",
    "wm_confirm": "Delete this message? (yes/no)", "wm_ok": "Message deleted", "wm_fail": "Delete failed",
    "wx_title": "Webhook Editor", "wx_desc": "Rename, change avatar, or clear avatar (PATCH)",
    "wx_mode_name": "Rename", "wx_mode_avatar": "Change avatar", "wx_mode_clear": "Clear avatar",
    "wx_name": "New name (Enter = skip)", "wx_avatar": "Avatar image URL (Enter = skip)",
    "wx_avatar_fail": "Could not load avatar", "wx_nothing": "Nothing to update",
    "wx_patch": "Updating webhook…", "wx_ok": "Webhook updated", "wx_fail": "Update failed",
    "wrn_title": "Rename Webhook", "wrn_desc": "Quick rename via PATCH",
    "wrn_ok": "Renamed", "wrn_fail": "Rename failed",
    "wc_title": "Webhook Cloner", "wc_desc": "Copy name & avatar to another webhook",
    "wc_source": "Source webhook URL", "wc_target": "Target webhook URL",
    "wc_running": "Cloning…", "wc_ok": "Cloned", "wc_fail": "Clone failed",
    "wc_fail_src": "Source webhook invalid",
    "wex_title": "URL Extractor", "wex_desc": "Parse ID, token & API URLs from webhook link",
    "wsf_title": "Snowflake Decoder", "wsf_desc": "Decode webhook ID creation timestamp",
    "wsf_invalid": "Invalid snowflake ID",
    "wb_title": "Bulk Checker", "wb_desc": "Validate multiple webhook URLs at once",
    "wb_prompt": "URL or type file", "wb_file": ".txt file path",
    "wb_running": "Checking…", "wb_result": "Bulk check", "wb_valid": "Valid",
    "wl_title": "Webhook Library", "wl_desc": "Save & manage webhook URLs locally",
    "wl_save": "Save webhook", "wl_list": "List saved", "wl_remove": "Remove saved",
    "wl_label": "Label name", "wl_saved": "Saved", "wl_removed": "Removed from library",
    "wl_not_found": "Label not found", "wl_empty": "Library empty — save a webhook first",
    "wcu_title": "Curl Generator", "wcu_desc": "Generate curl commands for this webhook",
    "wcu_hint": "Copy/paste into terminal (careful with DELETE)",
    "wbd_title": "Bulk Destroyer", "wbd_desc": "Delete multiple webhooks from a list",
    "wbd_confirm": "Delete ALL listed webhooks? (yes/no)",
    "wd_title": "Webhook Destroyer", "wd_desc": "Delete one webhook or bulk-delete from a list",
    "wd_single": "Single webhook", "wd_bulk": "Bulk delete (list)",
    "wd_confirm": "Delete this webhook? (yes/no)", "wd_ok": "Deleted", "wd_fail": "Failed",
    "wav_title": "Avatar Changer", "wav_desc": "Change webhook avatar from file or URL (KoalaHook)",
    "wav_source": "Image path or URL", "wav_ok": "Avatar updated", "wav_fail": "Avatar update failed",
    "wca_title": "Clear Avatar", "wca_desc": "Remove webhook avatar (PATCH null)",
    "wca_confirm": "Remove avatar? (yes/no)", "wca_ok": "Avatar cleared", "wca_fail": "Clear failed",
    "wef_title": "Embed Fields", "wef_desc": "Send embed with inline fields (DisHook-style)",
    "wef_fields_hint": "Up to 5 fields, empty name to stop",
    "wef_fname": "Field name", "wef_fval": "Field value", "wef_ok": "Embed sent", "wef_fail": "Failed",
    "wme_title": "Multi-Embed", "wme_desc": "Send multiple embeds in one message (max 10)",
    "wme_count": "Embed count (2-10, default 3)", "wme_ok": "Sent", "wme_fail": "Failed",
    "wim_title": "Impersonate Send", "wim_desc": "Override username & avatar per message",
    "wim_avatar": "Avatar URL (optional)", "wim_ok": "Sent", "wim_fail": "Failed",
    "wsi_title": "Silent Send", "wsi_desc": "Send without notification (SUPPRESS_NOTIFICATIONS)",
    "wsi_ok": "Silent message sent", "wsi_fail": "Failed",
    "wmc_title": "Mentions Control", "wmc_desc": "Control allowed_mentions (discord-webhook-kit)",
    "wmc_block": "Block all mentions", "wmc_everyone": "Allow @everyone",
    "wmc_here": "Allow @here", "wmc_all": "Allow all mentions",
    "wmc_ok": "Sent with mention rules", "wmc_fail": "Failed",
    "wrt_title": "Rate Limit Test", "wrt_desc": "Burst requests & show 429 / Retry-After headers",
    "wrt_bursts": "Burst count (3-15, default 8)", "wrt_result": "Rate test",
    "wrt_rl": "Rate limits hit",
    "wpy_title": "Python Generator", "wpy_desc": "Generate discord-webhook Python code snippet",
    "wpy_hint": "pip install discord-webhook — github.com/lovvskillz/python-discord-webhook",
    "wfl_title": "Flood Spammer", "wfl_desc": "Infinite spam until Ctrl+C (KoalaHook-style)",
    "wfl_hint": "Ctrl+C to stop",
    "wfo_title": "Forum Thread", "wfo_desc": "Create forum post via thread_name",
    "wfo_name": "Thread/post title", "wfo_ok": "Forum post created", "wfo_fail": "Failed",
    "wcr_title": "Webhook Generator", "wcr_desc": "Create webhook via bot token + channel ID (Crimson-Wolf)",
    "wcr_token": "Bot token", "wcr_no_token": "Bot token required — enter it in the console",
    "wcr_channel": "Channel ID", "wcr_channel_invalid": "Invalid channel ID",
    "wcr_name": "Webhook name", "wcr_ok": "Webhook created — join https://discord.gg/007tools", "wcr_fail": "Create failed",
    "wst_title": "Sticker Sender", "wst_desc": "Send a Discord sticker via webhook",
    "wst_id": "Sticker ID", "wst_invalid": "Invalid sticker ID",
    "wst_ok": "Sticker sent", "wst_fail": "Sticker failed (needs Nitro sticker or guild sticker)",
}

if __name__ == "__main__":
    set_language(STRINGS)
    run_tool(sys.argv[1] if len(sys.argv) > 1 else "")
