import sys
if hasattr(sys.stdout, 'reconfigure'): sys.stdout.reconfigure(encoding='utf-8')
import os, time, math
from rich.console import Console
from rich.panel import Panel
from rich.text import Text
from rich.align import Align
from rich.table import Table
from rich import box

console = Console()

ASCII = r"""
  ██████╗  ██████╗ ██╗  ██╗     ██████╗██████╗ ███████╗ █████╗ ████████╗ ██████╗ ██████╗ 
  ██╔══██╗██╔═══██╗╚██╗██╔╝    ██╔════╝██╔══██╗██╔════╝██╔══██╗╚══██╔══╝██╔═══██╗██╔══██╗
  ██║  ██║██║   ██║ ╚███╔╝     ██║     ██████╔╝█████╗  ███████║   ██║   ██║   ██║██████╔╝
  ██║  ██║██║   ██║ ██╔██╗     ██║     ██╔══██╗██╔══╝  ██╔══██║   ██║   ██║   ██║██╔══██╗
  ██████╔╝╚██████╔╝██╔╝ ██╗    ╚██████╗██║  ██║███████╗██║  ██║   ██║   ╚██████╔╝██║  ██║
  ╚═════╝  ╚═════╝ ╚═╝  ╚═╝     ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝
"""
SUBTITLE = "H I G H - F I D E L I T Y   D O S S I E R   G E N E R A T O R"

def boot():
    if sys.platform.startswith("win"):
        os.system("title WOCK // DOX CREATOR")
    os.system("cls" if os.name == "nt" else "clear")
    sys.stdout.write("\033[?25l")
    lines = ASCII.strip("\n").split("\n")
    t0 = time.time()
    try:
        while time.time() - t0 < 1.4:
            t = time.time() - t0
            sys.stdout.write("\033[H\n")
            for line in lines:
                sys.stdout.write(" ")
                for c, ch in enumerate(line):
                    if ch == " ":
                        sys.stdout.write(" ")
                    else:
                        v = max(40, min(255, int(100 + 155 * math.sin(t * 10 - c * 0.1))))
                        sys.stdout.write(f"\033[38;2;{v};0;0m{ch}")
                sys.stdout.write("\033[0m\n")
            sys.stdout.write(f"\n  \033[38;2;80;0;0m{SUBTITLE}\033[0m\n")
            sys.stdout.flush()
            time.sleep(0.025)
    finally:
        sys.stdout.write("\033[?25h\033[0m")
    os.system("cls" if os.name == "nt" else "clear")

def ask_field(prompt):
    return console.input(f" [red]─▶[/] [white]{prompt}: [/]").strip() or "N/A"

if __name__ == "__main__":
    try:
        boot()
        console.print(Align.center(Panel(
            Text.from_markup("[bold red]WOCK-TOOLS[/]  [dim]//[/]  [white]DOX CREATOR[/]  [dim]//[/]  [red]OSINT[/]"),
            border_style="red", padding=(0, 6)
        )))
        console.print()

        console.print(" [bold red]┌─[[/][bold white] Filename [/][bold red]][/]")
        fn = console.input(" [bold red]└─▶[/] [bold white]").strip() or "dox_output"

        data = {}
        sections = {
            "IDENTITY": ["Last Name", "First Name", "Age", "Date of Birth", "City", "Address"],
            "CONTACTS": ["Email", "Phone", "Discord", "Instagram", "Twitter"],
            "FAMILY":   ["Father's Name", "Father's Work", "Mother's Name", "Mother's Work"],
            "HARDWARE": ["IP Address", "MAC Address", "PC Model", "OS"]
        }

        for sec, fields in sections.items():
            console.print(f"\n [bold red]── {sec} ──[/]")
            for f in fields:
                data[f] = ask_field(f)

        save_path = os.path.join(os.getcwd(), "Wock - Output", "Save-Dox")
        if not os.path.exists(save_path): os.makedirs(save_path, exist_ok=True)
        final_file = os.path.join(save_path, f"{fn}.txt")

        report = f"""
  ╔══════════════════════════════════════════════════════════════════╗
  ║                 WOCK-MULTI // INFORMATION DOSSIER                ║
  ╚══════════════════════════════════════════════════════════════════╝

  [+] IDENTITY
  > Last Name : {data.get('Last Name')}
  > First Name : {data.get('First Name')}
  > Age : {data.get('Age')}
  > Born on : {data.get('Date of Birth')}
  > City : {data.get('City')}
  > Address : {data.get('Address')}

  [+] CONTACTS
  > Email : {data.get('Email')}
  > Phone : {data.get('Phone')}
  > Discord : {data.get('Discord')}
  > Instagram : {data.get('Instagram')}
  > Twitter : {data.get('Twitter')}

  [+] FAMILY
  > Father : {data.get("Father's Name")} ({data.get("Father's Work")})
  > Mother : {data.get("Mother's Name")} ({data.get("Mother's Work")})

  [+] HARDWARE
  > IP : {data.get('IP Address')}
  > MAC : {data.get('MAC Address')}
  > Machine : {data.get('PC Model')} ({data.get('OS')})

  Generated by Wock-Multi v2.0 PRIME
"""
        with open(final_file, "w", encoding="utf-8") as f: f.write(report)

        console.print(f"\n [bold green][✓] Dossier saved : {final_file}[/]")
        console.input("\n [dim]Press [bold red]ENTER[/] to exit...[/]")

    except (KeyboardInterrupt, EOFError):
        pass
